ComfyUI-NormalCrafterWrapper

Cannot import /workspace/ComfyUI/custom_nodes/ComfyUI-NormalCrafterWrapper module for custom nodes: Failed to import diffusers.models.autoencoders.autoencoder_kl_temporal_decoder because of the following error (look up to see its traceback):                             Command '['/usr/bin/gcc', '/tmp/tmpk8dpd0gg/main.c', '-O3', '-shared', '-fPIC', '-Wno-psabi', '-o', '/tmp/tmpk8dpd0gg/cuda_utils.cpython-311-x86_64-linux-gnu.so', '-lcuda', '-L/usr/local/lib/python3.11/dist-packages/triton/backends/nvidia/lib', '-L/lib/x86_64-linux-gnu', '-I/usr/local/lib/python3.11/dist-packages/triton/backends/nvidia/include', '-I/tmp/tmpk8dpd0gg', '-I/usr/include/python3.11']' returned non-zero exit status 1.                                                                                                            /usr/local/lib/python3.11/dist-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)                              --------------


File "/usr/local/lib/python3.11/dist-packages/diffusers/utils/import_utils.py", line 820, in _get_module                                 return importlib.import_module("." + module_name, self.__name__)                                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                     File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module                                                             return _bootstrap._gcd_import(name[level:], package, level)                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                          File "<frozen importlib._bootstrap>", line 1204, in _gcd_import                                                                        File "<frozen importlib._bootstrap>", line 1176, in _find_and_load                                                                     File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked                                                            File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed                                                           File "<frozen importlib._bootstrap>", line 1204, in _gcd_import                                                                        File "<frozen importlib._bootstrap>", line 1176, in _find_and_load                                                                     File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked                                                            File "<frozen importlib._bootstrap>", line 690, in _load_unlocked                                                                      File "<frozen importlib._bootstrap_external>", line 940, in exec_module                                                                File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed                                                           File "/usr/local/lib/python3.11/dist-packages/diffusers/models/autoencoders/__init__.py", line 1, in <module>                            from .autoencoder_asym_kl import AsymmetricAutoencoderKL                                                                             File "/usr/local/lib/python3.11/dist-packages/diffusers/models/autoencoders/autoencoder_asym_kl.py", line 22, in <module>                from ..modeling_utils import ModelMixin                                                                                              File "/usr/local/lib/python3.11/dist-packages/diffusers/models/modeling_utils.py", line 40, in <module>                                  from ..quantizers import DiffusersAutoQuantizer, DiffusersQuantizer                                                                  File "/usr/local/lib/python3.11/dist-packages/diffusers/quantizers/__init__.py", line 15, in <module>                                    from .auto import DiffusersAutoQuantizer                                                                                             File "/usr/local/lib/python3.11/dist-packages/diffusers/quantizers/auto.py", line 22, in <module>                                        from .bitsandbytes import BnB4BitDiffusersQuantizer, BnB8BitDiffusersQuantizer                                                       File "/usr/local/lib/python3.11/dist-packages/diffusers/quantizers/bitsandbytes/__init__.py", line 2, in <module>                        from .utils import dequantize_and_replace, dequantize_bnb_weight, replace_with_bnb_linear                                            File "/usr/local/lib/python3.11/dist-packages/diffusers/quantizers/bitsandbytes/utils.py", line 32, in <module>                          import bitsandbytes as bnb                                                                                                           File "/usr/local/lib/python3.11/dist-packages/bitsandbytes/__init__.py", line 19, in <module>                                            from .nn import modules                                                                                                              File "/usr/local/lib/python3.11/dist-packages/bitsandbytes/nn/__init__.py", line 21, in <module>                                         from .triton_based_modules import (                                                                                                  File "/usr/local/lib/python3.11/dist-packages/bitsandbytes/nn/triton_based_modules.py", line 6, in <module>
   from bitsandbytes.triton.dequantize_rowwise import dequantize_rowwise
  File "/usr/local/lib/python3.11/dist-packages/bitsandbytes/triton/dequantize_rowwise.py", line 18, in <module>
    @triton.autotune(
     ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/triton/runtime/autotuner.py", line 378, in decorator
    return Autotuner(fn, fn.arg_names, configs, key, reset_to_zero, restore_value, pre_hook=pre_hook,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/triton/runtime/autotuner.py", line 130, in __init__
    self.do_bench = driver.active.get_benchmarker()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/triton/runtime/driver.py", line 23, in __getattr__
    self._initialize_obj()
  File "/usr/local/lib/python3.11/dist-packages/triton/runtime/driver.py", line 20, in _initialize_obj
    self._obj = self._init_fn()
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/triton/runtime/driver.py", line 9, in _create_driver
    return actives[0]()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/triton/backends/nvidia/driver.py", line 535, in __init__
    self.utils = CudaUtils()  # TODO: make static
                 ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/triton/backends/nvidia/driver.py", line 89, in __init__
    mod = compile_module_from_src(Path(os.path.join(dirname, "driver.c")).read_text(), "cuda_utils")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/triton/backends/nvidia/driver.py", line 66, in compile_module_from_src
    so = _build(name, src_path, tmpdir, library_dirs(), include_dir, libraries)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/triton/runtime/build.py", line 36, in _build
    subprocess.check_call(cc_cmd, stdout=subprocess.DEVNULL)
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/gcc', '/tmp/tmpk8dpd0gg/main.c', '-O3', '-shared', '-fPIC', '-Wno-psabi', '-o', '/tmp/tmpk8dpd0gg/cuda_utils.cpython-311-x86_64-linux-gnu.so', '-lcuda', '-L/usr/local/lib/python3.11/dist-packages/triton/backends/nvidia/lib', '-L/lib/x86_64-linux-gnu', '-I/usr/local/lib/python3.11/dist-packages/triton/backends/nvidia/include', '-I/tmp/tmpk8dpd0gg', '-I/usr/include/python3.11']' returned non-zero exit status 1.                                                                                                                                                                                                                    The above exception was the direct cause of the following exception:
